jenkins-master:
  container_name: jenkins-container
  build: .
  ports:
    - "49009:8080"
    - "50009:50000"
  volumes:
    - /data/jenkins_home/jobs:/var/jenkins_home/jobs
  env_file:
    - ./settings.env
  restart: always
